class android.support.v4.content.ModernAsyncTask$3 extends java.util.concurrent.FutureTask
{
    final android.support.v4.content.ModernAsyncTask this$0;

    void <init>(android.support.v4.content.ModernAsyncTask, java.util.concurrent.Callable)
    {
        android.support.v4.content.ModernAsyncTask$3 $r0;
        android.support.v4.content.ModernAsyncTask $r1;
        java.util.concurrent.Callable $r2;

        $r0 := @this: android.support.v4.content.ModernAsyncTask$3;
        $r1 := @parameter0: android.support.v4.content.ModernAsyncTask;
        $r2 := @parameter1: java.util.concurrent.Callable;
        $r0.<android.support.v4.content.ModernAsyncTask$3: android.support.v4.content.ModernAsyncTask this$0> = $r1;
        specialinvoke $r0.<java.util.concurrent.FutureTask: void <init>(java.util.concurrent.Callable)>($r2);
        return;
    }

    protected void done()
    {
        android.support.v4.content.ModernAsyncTask$3 $r0;
        java.lang.InterruptedException $r1;
        java.lang.Object $r2;
        java.lang.Throwable $r3;
        android.support.v4.content.ModernAsyncTask $r4;
        java.util.concurrent.ExecutionException $r6;
        java.lang.RuntimeException $r7;
        java.util.concurrent.CancellationException $r8;

        $r0 := @this: android.support.v4.content.ModernAsyncTask$3;

     label0:
        $r2 = virtualinvoke $r0.<android.support.v4.content.ModernAsyncTask$3: java.lang.Object get()>();
        $r4 = $r0.<android.support.v4.content.ModernAsyncTask$3: android.support.v4.content.ModernAsyncTask this$0>;
        staticinvoke <android.support.v4.content.ModernAsyncTask: void access$400(android.support.v4.content.ModernAsyncTask,java.lang.Object)>($r4, $r2);

     label1:
        return;

     label2:
        $r1 := @caughtexception;
        staticinvoke <android.util.Log: int w(java.lang.String,java.lang.Throwable)>("AsyncTask", $r1);
        goto label1;

     label3:
        $r6 := @caughtexception;
        $r7 = new java.lang.RuntimeException;
        $r3 = virtualinvoke $r6.<java.util.concurrent.ExecutionException: java.lang.Throwable getCause()>();
        specialinvoke $r7.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occured while executing doInBackground()", $r3);
        throw $r7;

     label4:
        $r8 := @caughtexception;
        $r4 = $r0.<android.support.v4.content.ModernAsyncTask$3: android.support.v4.content.ModernAsyncTask this$0>;
        staticinvoke <android.support.v4.content.ModernAsyncTask: void access$400(android.support.v4.content.ModernAsyncTask,java.lang.Object)>($r4, null);
        goto label1;

     label5:
        $r3 := @caughtexception;
        $r7 = new java.lang.RuntimeException;
        specialinvoke $r7.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occured while executing doInBackground()", $r3);
        throw $r7;

        catch java.lang.InterruptedException from label0 to label1 with label2;
        catch java.util.concurrent.ExecutionException from label0 to label1 with label3;
        catch java.util.concurrent.CancellationException from label0 to label1 with label4;
        catch java.lang.Throwable from label0 to label1 with label5;
    }
}
